export const ADD_DISHES = 'ADD_DISHES';
export const DISHES_LOADING = 'DISHES_LOADING';
export const FAILED_DISHES = 'FAILED_DISHES';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const FAILED_COMMENTS = 'FAILED_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const FAILED_PROMOS = 'FAILED_PROMOS';

export const ADD_LEADERS = 'ADD_LEADERS';
export const LEADERS_LOADING = 'LEADERS_LOADING';
export const FAILED_LEADERS = 'FAILED_LEADERS';

export const POST_FAVORITE = 'POST_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';